# Generated by Django 3.2.16 on 2023-12-06 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20231206_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_caption',
        ),
    ]
