# Generated by Django 3.2.16 on 2023-12-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_addcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_caption',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='addcomment',
            name='text',
            field=models.TextField(verbose_name='Оставить комментарий'),
        ),
    ]
