# Generated by Django 3.2.16 on 2023-12-17 20:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_rename_comment_addcomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddComment',
            new_name='Comment',
        ),
    ]
