version: '3'

volumes:
  pg_data:

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env
  telegram_bot:
    image: zavjalovaue/school_21_community_bot_1-telegram_bot:latest
    env_file: .env
    ports:
      - 8080:8080
    depends_on: 
      - db
