"""First migration

Revision ID: 89262db89c31
Revises: 710a097699b4
Create Date: 2024-09-30 00:08:48.679516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89262db89c31'
down_revision = '710a097699b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
